services:
  service.discovery:
    ports:
      - 8761:8761
    build:
      context: ServiceDiscovery
    container_name: service.discovery
  authorization.manager:
    ports:
      - 10001:10001
    build:
      context: AuthorizationManager
    container_name: authorization.manager
    depends_on:
      - service.discovery
  account.manager:
    ports:
      - 10002:10002
    build:
      context: AccountManager
    container_name: account.manager
    depends_on:
      - service.discovery
      - authorization.manager
      - database
  database:
    image: postgres:latest
    restart: always
    container_name: database
    environment:
      POSTGRES_DB: videostreaming
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
