services:
  service.discovery:
    ports:
      - 8761:8761
    build:
      context: ServiceDiscovery
    container_name: service.discovery
  authorization.manager:
    ports:
      - 10001:10001
    build:
      context: AuthorizationManager
    container_name: authorization.manager
    depends_on:
      - service.discovery
