server:
  port: 10000
  servlet:
    context-path: /video
spring:
  application:
    name: video.streaming
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:100MB}
      max-request-size: ${MAX_FILE_SIZE:100MB}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://service.discovery:8761/eureka}
  instance:
    preferIpAddress: true

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true

###################################### Async Config
async:
  task:
    executor:
      poolSize:
        core: 10
        max: 10
      keepAliveTime: 60
      queueCapacity: 500
      threadNamePrefix: VideoStreaming-
