server:
  port: 10001
  servlet:
    context-path: /auth

spring:
  application:
    name: authorization.manager

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://service.discovery:8761/eureka}
  instance:
    preferIpAddress: true
