server:
  port: 10003
  servlet:
    context-path: /stats
spring:
  application:
    name: statistics.manager
  security:
    props:
      secret: ${SECURITY_SECRET:} # only for HS256
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://database:5432/videostreaming}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: POSTGRESQL
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: ${KAFKA_URL:kafka:29092}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://service.discovery:8761/eureka}
  instance:
    preferIpAddress: true

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true

public:
  endpoints: /actuator,/actuator/health,/actuator/info
