server:
  port: 10003
  servlet:
    context-path: /stats
spring:
  application:
    name: statistics.manager
  security:
    props:
      secret: ${SECURITY_SECRET:} # only for HS256
  jackson:
    deserialization:
      fail-on-unknown-properties: false


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://service.discovery:8761/eureka}
  instance:
    preferIpAddress: true

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true

public:
  endpoints: /actuator,/actuator/health,/actuator/info
